# Generated by Django 5.1.3 on 2024-11-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productinformation_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_information', to='product_module.productinformation', verbose_name='اطلاعات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='size',
            field=models.CharField(blank=True, max_length=300, verbose_name='سایز'),
        ),
    ]
