# Generated by Django 5.1.3 on 2024-11-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_alter_product_product_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300, verbose_name='برچسپ')),
            ],
            options={
                'verbose_name': 'برچسپ محصول',
                'verbose_name_plural': 'برچسپ های محصولات',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='productinformation',
            options={'verbose_name': 'اطلاعات تکمیلی', 'verbose_name_plural': 'تمام اطلاعات تکمیلی'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(to='product_module.producttag', verbose_name='تگهای محصول'),
        ),
    ]
