# Generated by Django 5.1.3 on 2024-12-21 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 12, 21), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
