# Generated by Django 5.1.3 on 2025-01-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_articlescomment'),
        ('article_module', '0008_articlecomment'),
    ]

    operations = [
    ]
