# Generated by Django 5.1.3 on 2025-01-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_merge_0007_articlescomment_0008_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان مقاله'),
        ),
        migrations.DeleteModel(
            name='ArticlesComment',
        ),
    ]
