# Generated by Django 5.1.3 on 2025-01-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_alter_articlecomment_options'),
        ('article_module', '0010_alter_articlecomment_options_alter_article_title_and_more'),
    ]

    operations = [
    ]
